CREATE TABLE NAV_CONF(
    NC_ID_ELEMENTO    INT    NOT NULL   AUTO_INCREMENT,
    NC_DESCRIPCION    VARCHAR(100)    NOT NULL,
    NC_HREF           VARCHAR(230)    NOT NULL,
    NC_ID_PADRE       INT             NULL,
    PRIMARY KEY(NC_ID_ELEMENTO)
);

CREATE TABLE SLIDER_CONF(
    SC_ID_IMG        INT    NOT NULL   AUTO_INCREMENT,
    SC_NOMBRE        VARCHAR(150) NOT NULL,
    SC_URL           VARCHAR(50)  NOT NULL,
    SC_HREF          VARCHAR(250) NOT NULL,
    
);